INSERT INTO tb_customers(name, email, password) VALUES ('Loki Odinson', 'loki@email.com', 'loki>thor');
INSERT INTO tb_customers(name, email, password) VALUES ('Logan', 'logan@email.com', 'deadpool');
INSERT INTO tb_customers(name, email, password) VALUES ('Gandalf', 'gan@email.com', 'eu_nunca_me_atraso');
INSERT INTO tb_customers(name, email, password) VALUES ('Thor Odinson', 'thor@email.com', 'mjolnir');
INSERT INTO tb_customers(name, email, password) VALUES ('Anakin', 'any@email.com', 'padawan_bom_é_padawan_mor');

INSERT INTO tb_books(client_id,name, price) VALUES (1, 'O Senhor dos Anéis', 29.99);
INSERT INTO tb_books(client_id,name, price) VALUES (2, 'Harry Potter e a Pedra Filosofal', 24.99);
INSERT INTO tb_books(client_id,name, price) VALUES (3, 'As Crônicas de Nárnia', 19.99);
INSERT INTO tb_books(client_id,name, price) VALUES (4, 'Dom Quixote', 34.99);
INSERT INTO tb_books(client_id,name, price) VALUES (5, 'Orgulho e Preconceito', 22.99);
INSERT INTO tb_books(client_id,name, price) VALUES (5, 'O Pequeno Príncipe', 27.99);
INSERT INTO tb_books(client_id,name, price) VALUES (4, 'Inteligência Humilhada', 18.99);
INSERT INTO tb_books(client_id,name, price) VALUES (3, 'Confissões', 32.99);
INSERT INTO tb_books(client_id,name, price) VALUES (2, 'Tomás de Aquino e o Conhecimento de Deus', 21.99);
INSERT INTO tb_books(client_id,name, price) VALUES (1, 'O Hobbit', 26.99);
INSERT INTO tb_books(client_id,name, price) VALUES (1, 'Percy Jackson e o Ladrão de Raios', 39.99);
INSERT INTO tb_books(client_id,name, price) VALUES (3, 'Harry Potter e o Cálice de Fogo', 23.99);
INSERT INTO tb_books(client_id,name, price) VALUES (5, 'O Silmarillion', 15.99);
INSERT INTO tb_books(client_id,name, price) VALUES (2, 'O Herói Perdido', 26.99);
INSERT INTO tb_books(client_id,name, price) VALUES (4, 'O Grande Gatsby', 56.99);
INSERT INTO tb_books(client_id,name, price) VALUES (4, 'Viland Saga', 16.99);
INSERT INTO tb_books(client_id,name, price) VALUES (2, 'Berserk', 22.99);
INSERT INTO tb_books(client_id,name, price) VALUES (5, 'Vagabond', 36.99);
INSERT INTO tb_books(client_id,name, price) VALUES (3, 'Memórias Póstumas de Brás Cubas', 21.99);
INSERT INTO tb_books(client_id,name, price) VALUES (1, 'Dom Casmurro', 9.99);